// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Get expense (200 OK)",
    id: "a9ded43d-fa16-423c-ae24-b2f9229878e9",
    method: "GET",
    address:
      "http://localhost:8000/v1/expense/49088bff-de27-4be3-aef7-defb325ee954",
    data:
      '{\r\n  "amount": "00245607826611911348728974",\r\n  "category": "changed",\r\n  "description": "changed"\r\n}'
  });

  postman[Request]({
    name: "Get Summary (200 OK)",
    id: "43693aca-d00e-474c-8d60-82371d532d74",
    method: "GET",
    address:
      "http://localhost:8000/v1/expense/49088bff-de27-4be3-aef7-defb325ee954",
    data:
      '{\r\n  "amount": "00245607826611911348728974",\r\n  "category": "changed",\r\n  "description": "changed"\r\n}'
  });

  postman[Request]({
    name: "List Expenses (200 OK)",
    id: "2e8d1cbc-6620-4fc0-81f8-e67d7b47b8d3",
    method: "GET",
    address: "http://localhost:8000/v1/expense?limit=10&offset=2"
  });
}

